"""Implementation of the `asc apply` command."""

from __future__ import annotations

import argparse
from pathlib import Path

from asc.core.report import load_report
from asc.core.selection import select_findings


LOW_CONFIDENCE_VALUES = {"low"}


def add_apply_parser(
    subparsers: argparse._SubParsersAction,
) -> argparse.ArgumentParser:
    """
    Register the apply command with the top-level parser.

    Usage:
        asc apply report.json 1
        asc apply report.json 1 3 5
        asc apply report.json -a
    """

    parser = subparsers.add_parser(
        "apply",
        usage="asc apply [-h] [-a] report [id ...]",
        help="Select fixes from a generated report.",
        description=(
            "Load an ASC report and select findings for remediation. "
            "Task 1.2 validates selection only; automatic remediation "
            "will be implemented in Task 4.1."
        ),
    )

    parser.add_argument(
        "report",
        help="Path to a report generated by `asc analyze`.",
    )

    parser.add_argument(
        "ids",
        nargs="*",
        metavar="id",
        help="One or more finding IDs separated by spaces.",
    )

    parser.add_argument(
        "-a",
        "--all",
        action="store_true",
        help="Select every finding in the report.",
    )

    parser.set_defaults(
        handler=run_apply,
        command_parser=parser,
    )

    return parser


def run_apply(args: argparse.Namespace) -> int:
    """
    Validate report and selected finding IDs.

    This command prepares the public workflow for later remediation.
    It intentionally does not modify source code yet.
    """

    report_path = Path(args.report)
    report = load_report(report_path)
    selected_findings = select_findings(
        report=report,
        requested_ids=args.ids,
        select_all=args.all,
    )

    if not selected_findings:
        print(f"Report has no findings: {report_path}")
        return 0

    print(
        f"Selected {len(selected_findings)} finding(s) "
        f"from {report_path}."
    )
    print(
        "Automatic remediation will be implemented in Task 4.1."
    )

    if _contains_low_confidence_finding(selected_findings):
        print(
            "Note: low-confidence findings may not include suggested "
            "replacements. You can ask the IDE agent to help create a fix."
        )

    return 0


def _contains_low_confidence_finding(findings: list) -> bool:
    """
    Return whether any selected finding is low confidence.
    """

    return any(
        str(finding.get("confidence", "")).lower()
        in LOW_CONFIDENCE_VALUES
        for finding in findings
        if isinstance(finding, dict)
    )
