"""Implementation of the `asc apply` command."""

from __future__ import annotations

import argparse
from pathlib import Path

from asc.core.remediation import apply_selected_fixes
from asc.core.report import load_report
from asc.core.selection import select_findings


def add_apply_parser(
    subparsers: argparse._SubParsersAction,
) -> argparse.ArgumentParser:
    """
    Register the apply command with the top-level parser.

    Usage:
        asc apply report.json 1
        asc apply report.json 1 3 5
        asc apply report.json -a
    """

    parser = subparsers.add_parser(
        "apply",
        usage="asc apply [-h] [-a] report [id ...]",
        help="Apply fixes from a generated report.",
        description=(
            "Load an ASC report and apply selected automatic fixes "
            "to the report source file."
        ),
    )

    parser.add_argument(
        "report",
        help="Path to a report generated by `asc analyze`.",
    )

    parser.add_argument(
        "ids",
        nargs="*",
        metavar="id",
        help="One or more finding IDs separated by spaces.",
    )

    parser.add_argument(
        "-a",
        "--all",
        action="store_true",
        help="Select every finding in the report.",
    )

    parser.set_defaults(
        handler=run_apply,
        command_parser=parser,
    )

    return parser


def run_apply(args: argparse.Namespace) -> int:
    """
    Apply selected report fixes to the source file.
    """

    report_path = Path(args.report)
    report = load_report(report_path)
    selected_findings = select_findings(
        report=report,
        requested_ids=args.ids,
        select_all=args.all,
    )

    if not selected_findings:
        print(f"Report has no findings: {report_path}")
        return 0

    result = apply_selected_fixes(
        report=report,
        selected_findings=selected_findings,
    )

    for message in result["skipped"]:
        print(message)

    if result["applied"] == 0:
        print("No automatic fixes were applied.")
        return 0

    print(
        f"Applied {result['applied']} fix(es) to "
        f"{result['source_path']}."
    )

    return 0
